### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sonemelody** [sonemelody/Weather#2]
- [x] 메인화면의 floating button 수정 -> + 버튼만 남기고 나머지 지우기
- [ ] fragment_calendar.xml -> date picker
- [x] fragment_gallery.xml -> spinner
- [x] 로그인 및 회원가입 페이지 디자인
- [x] home fragment에서 날씨 위젯, 슬라이드 갤러리 적용 안 되는 문제 해결하기
- [x] 메인화면 ui 디자인
- [x] drawable 메뉴 ui 디자인 -> 폰트 크기 변경 및 텍스트 컬러 변경
- [x] nav header
- [x] floating button 애니메이션 수정
- [x] 날씨 위젯 ui 수정
